CREATE TABLE Authors
(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    Name VARCHAR(255),
    Biography TEXT,
    CreatedAt DATETIME DEFAULT (NOW()),
    UpdatedAt DATETIME DEFAULT (NOW())
);

INSERT INTO Authors (Name, Biography, CreatedAt, UpdatedAt) VALUES
	 ('Pearson Education Asia','Minus qui velit modi est aut et dolor qui. Dolore et ratione nulla est cumque amet consequatur. Veniam assumenda cum molestias voluptatum quae tempora. Pariatur est sit quis deleniti. Dolorem explicabo recusandae expedita vel facere possimus. Adipisci fugit placeat consequatur et. Dignissimos ipsa et dolor ducimus quia sunt voluptatibus.','2023-12-13 16:35:26','2023-12-13 16:35:26'),
	 ('Prentice Hall PTR','Et doloremque blanditiis voluptate aspernatur. Repellat quae eos dolor ut porro ut. Nostrum ad eveniet minus. Accusamus dolorem iure voluptatem quia ex et. Amet aut labore sunt iste qui qui quam fuga. Laborum soluta porro rerum impedit. Et similique veritatis excepturi iusto perferendis. Voluptatem placeat officiis et repellendus et debitis in.','2023-12-13 16:35:26','2023-12-13 16:35:26'),
	 ('Pearson','Quo incidunt doloribus ab ea. Aut qui doloremque ipsam sed dicta nesciunt. Rerum dolore provident cum neque non. Nemo cum labore ut quia et et. Illo ut et repellendus ratione itaque eum. At nesciunt accusantium sit suscipit omnis eius. Dolores cupiditate accusantium explicabo autem qui quo non.','2023-12-13 16:35:27','2023-12-13 16:35:27'),
	 ('Prentice Hall','Voluptatem delectus quia suscipit adipisci provident. Quos omnis voluptates enim veritatis modi non id. Quia molestias qui est nemo esse beatae.','2023-12-13 16:35:27','2023-12-13 16:35:27'),
	 ('人民邮电出版社','Vel rem accusamus veritatis ullam omnis quas nobis. Esse rerum commodi cum enim. Ab minima magni dolor. Unde voluptates enim id consequuntur adipisci porro. Eius qui ullam veniam ut dignissimos in. Quia sed consequuntur eum quia labore qui exercitationem. At architecto aut fugit distinctio. Quis quibusdam ut ex et corrupti eos explicabo est.','2023-12-13 16:35:27','2023-12-13 16:35:27'),
	 ('Pearson Education Limited','Consequatur quas et veniam harum sint odit vel. Repudiandae et et repellat totam deserunt dolorum. Explicabo quidem delectus dignissimos officia ipsa molestiae qui. Ab ratione reprehenderit aut optio cum. Velit explicabo sed quibusdam perferendis praesentium. Autem dolores ad maxime quia fuga.','2023-12-13 16:35:27','2023-12-13 16:35:27'),
	 ('mitp','Ut repellendus qui maxime necessitatibus. Non qui quod maxime id sint perspiciatis. Quo est vel ipsum ut in. Doloribus est consequatur cum perferendis similique. Quas quia repudiandae ut eveniet nihil. Vel debitis id hic ut vitae. Corporis asperiores sint consequatur velit numquam provident quas.','2023-12-13 16:35:27','2023-12-13 16:35:27'),
	 ('ANAYA MULTIMEDIA','Repellat nobis ea aut repudiandae recusandae. Harum aliquam qui autem deserunt fugiat. Quaerat quaerat non et dolores architecto sed. Sit autem saepe quo unde minus consequatur non. Qui amet et asperiores tempore laudantium dolores.','2023-12-13 16:35:27','2023-12-13 16:35:27'),
	 ('Kiskapu','Dicta qui vel eligendi debitis architecto deleniti. Eos occaecati velit fuga iusto quidem quisquam. Debitis possimus in vitae velit debitis. Quis sed vitae nesciunt velit inventore officia. Commodi ipsum velit fuga at quia. Tempore perferendis quis maiores officia earum minus.','2023-12-13 16:35:27','2023-12-13 16:35:27'),
	 ('Cambridge University Press','Suscipit ab voluptatum cupiditate aut. Cupiditate perspiciatis odio non vero minus. Aut odio error dolores non. Repudiandae ipsum aut eum quod. Magni in optio quis nihil autem. Et qui dolorem praesentium doloremque dolores voluptates.','2023-12-13 16:35:27','2023-12-13 16:35:27');
INSERT INTO Authors (Name, Biography, CreatedAt, UpdatedAt) VALUES
	 ('Pearson France','Et et et magnam suscipit eaque facere amet. Est sit ducimus harum sed quos sit. Explicabo et et omnis dolore quas beatae corrupti dicta. Corrupti dolor quaerat dolorem doloribus voluptatum. Dolorem maxime earum eos quibusdam error modi. Eum aliquam id incidunt qui.','2023-12-13 16:35:27','2023-12-13 16:35:27'),
	 ('Addison-Wesley Professional','Ut enim quia minima voluptatem aut. Ipsum rerum et magni reiciendis. Praesentium quasi sint sed totam. Molestias perspiciatis quaerat occaecati quo earum ut. Excepturi minima quis repellendus. Possimus ipsum tempora eius sed nesciunt.','2023-12-13 16:35:27','2023-12-13 16:35:27'),
	 ('Appleton-Century-Crofts','Alias voluptatum corrupti repellendus et et. Nisi iure ex doloribus aut aut quae. Nostrum consequuntur esse dolorem iste voluptatem fugiat dicta. Rerum vitae odit necessitatibus laudantium minima voluptas. Numquam nulla voluptate rerum deleniti. Rerum ipsa ipsa architecto id autem. Nobis nihil est et id nulla labore.','2023-12-13 16:35:27','2023-12-13 16:35:27'),
	 ('Helion','Iusto ratione blanditiis omnis debitis vitae corrupti et. Rerum magni cumque consequuntur quod laudantium. Voluptatibus fugit similique adipisci est repellendus ullam est. Amet ipsum et veniam aspernatur nesciunt labore reiciendis quos. Repellat qui ullam quos fuga. In assumenda nobis impedit magnam numquam iure. Id optio corporis est.','2023-12-13 16:35:27','2023-12-13 16:35:27'),
	 ('Apogeo','Provident voluptatem non vel culpa sed earum velit. Eaque omnis veniam ullam ipsum. Impedit et libero voluptas. Sit ex minima itaque nemo pariatur incidunt. Praesentium veniam error est voluptatum. Qui repudiandae delectus voluptatem hic ea. Perspiciatis velit sequi quis incidunt.','2023-12-13 16:35:27','2023-12-13 16:35:27'),
	 ('Addison-Wesley','Ea a est quo nisi. Ea non nulla eaque. Facere delectus dolorem dolor sed sapiente. Nihil consectetur repellendus fugiat aut. Est explicabo impedit possimus illo molestias pariatur quia sunt. Mollitia non eum totam ut. Voluptas rerum eum tempora itaque ut adipisci impedit. Et rem ex quae repellendus quam non.','2023-12-13 16:35:27','2023-12-13 16:35:27'),
	 ('Distributed by W.W. Norton','Est beatae molestiae porro ut. Dolores necessitatibus eum et consectetur assumenda sint. Omnis et laborum et provident. Quod fugiat omnis voluptas ad voluptatum.','2023-12-13 16:35:27','2023-12-13 16:35:27'),
	 ('G.K. Hall','Veritatis repellendus facilis odio aliquam. Recusandae ipsa molestias aut in est. Quisquam a numquam dolore molestiae hic. Quis ipsum exercitationem architecto officia sed sed laborum. Maiores et nobis quasi soluta sunt ut beatae. Et asperiores enim expedita possimus non. Qui ut facere ut beatae maiores consectetur.','2023-12-13 16:35:27','2023-12-13 16:35:27'),
	 ('Avon Books','Doloribus odio nulla ratione deleniti consequatur dolores eum. Unde animi aut necessitatibus. Debitis molestiae iure quia eos modi ut.','2023-12-13 16:35:27','2023-12-13 16:35:27'),
	 ('French and European Publications Inc','Quod consequuntur at necessitatibus porro molestiae magnam et. Et cum voluptate consectetur commodi. Provident voluptatem maiores aperiam eius et in voluptatem deserunt. Est aut hic tempore occaecati vitae impedit aut. Voluptas deserunt quos qui voluptatibus. Aut quia assumenda esse.','2023-12-13 16:35:27','2023-12-13 16:35:27');
INSERT INTO Authors (Name, Biography, CreatedAt, UpdatedAt) VALUES
	 ('Carlsen Verlag GmbH','Nemo natus numquam vel eaque et non sunt. Sit aut sunt architecto reiciendis quam. Temporibus laudantium quam in. Voluptatum ab temporibus qui enim est. Amet impedit sit vero commodi minima non incidunt voluptatibus. Omnis aspernatur deleniti vel nostrum in. Quos explicabo odit consequatur rem sit voluptatibus.','2023-12-13 16:35:28','2023-12-13 16:35:28'),
	 ('Brand: Raincoast Books','Id distinctio quae aut saepe doloremque porro velit. Incidunt ex non iusto quam voluptatem voluptatum aliquid qui. Illum quae est ut et vel. Consequatur amet autem molestiae aliquam et.','2023-12-13 16:35:29','2023-12-13 16:35:29'),
	 ('Bloomsbury UK','Fugiat dolores accusantium quo necessitatibus. Vitae fugit earum aspernatur asperiores repudiandae facilis beatae. Veniam nulla modi cumque quod. Optio qui ad voluptates et vero repellat.','2023-12-13 16:35:29','2023-12-13 16:35:29'),
	 ('Lulu Press, Inc.','Consequatur nam quod qui aut aspernatur et. Doloribus delectus dolor sed voluptas. Ut sit non voluptatibus consectetur aut. Sunt mollitia odio vitae architecto qui iste eaque. Necessitatibus vitae illum totam ut. Ea minima distinctio quo omnis commodi totam. Voluptatum error maiores sunt quisquam pariatur vitae.','2023-12-13 16:35:30','2023-12-13 16:35:30'),
	 ('salamandra','Dolores vero rerum sint rerum repellat. Dolorum et aliquid tenetur molestiae et. Quidem veritatis eos vel quia nisi. Quaerat unde iste nihil ut omnis. Ea quae consectetur rerum corporis voluptas debitis et commodi. Impedit deserunt consequatur similique laudantium. Qui ut ab dolor vel odit. Non qui sapiente voluptas qui ratione sequi velit.','2023-12-13 16:35:31','2023-12-13 16:35:31'),
	 ('Penguin Random House Grupo Editorial','Eligendi fugiat aut explicabo nam exercitationem nemo. Aut tempore sit saepe dolorem nostrum beatae. Aperiam cupiditate laudantium quo totam delectus accusantium blanditiis. Quidem mollitia reprehenderit autem autem qui architecto. Omnis omnis voluptates possimus ab. Consequuntur ut deleniti non maiores. Cupiditate quia omnis expedita rerum.','2023-12-13 16:35:31','2023-12-13 16:35:31'),
	 ('ROCCO','Molestias magni magni optio cumque nesciunt dolor. Qui et ab eveniet minima error. Quod sapiente voluptatem quis id neque. Omnis eos dolorum rem reiciendis. Distinctio repudiandae eius odio pariatur expedita quod.','2023-12-13 16:35:32','2023-12-13 16:35:32'),
	 ('Peoples Literature Publishing House','Porro tempora iure provident. Culpa temporibus omnis in consequatur facere eum. Qui aut qui sunt. Molestiae sit quisquam non recusandae voluptas. Amet praesentium quis hic nostrum illum nisi cumque. Officia ducimus rerum voluptatum magnam.','2023-12-13 16:35:32','2023-12-13 16:35:32'),
	 ('Distribooks','Unde tempora adipisci aliquam consequatur eius vitae. Laborum quae autem libero dolor soluta. Neque labore accusantium nisi asperiores id aspernatur voluptas quia. Nostrum saepe molestias quia dolor explicabo harum.','2023-12-13 16:35:32','2023-12-13 16:35:32'),
	 ('Nova Knjiga','Culpa sequi omnis itaque nesciunt reprehenderit beatae. Consequatur inventore enim corporis esse iusto. Mollitia quo cum accusantium sint blanditiis similique eligendi. Soluta deleniti rerum sunt ipsa et necessitatibus. Facere odio quasi vitae quaerat aut. Quo sed aut et consequatur. Veritatis aut dolorem dicta deleniti omnis quia ad.','2023-12-13 16:35:33','2023-12-13 16:35:33');
INSERT INTO Authors (Name, Biography, CreatedAt, UpdatedAt) VALUES
	 ('authur a. levine','Qui vero fugit modi aperiam et. Cupiditate et vitae iusto est rerum facere. Id suscipit ab fugit sit soluta. Nihil accusamus in ut repellat velit eveniet. Velit ipsam sit dolorum molestias nihil commodi sint. Cumque dolor aliquid laborum accusamus impedit non nihil voluptatem.','2023-12-13 16:35:33','2023-12-13 16:35:33'),
	 ('Huang guan wen hua chu ban you xian gong si','Consectetur qui et nihil odit qui rerum deserunt. Nemo maiores voluptas esse odio sunt. Est dolor at fugit est minus eveniet. Doloremque sit sunt laudantium sed. Saepe necessitatibus consequatur placeat aut amet magni. Ab dolor doloremque enim modi facere maiores.','2023-12-13 16:35:33','2023-12-13 16:35:33'),
	 ('Mulholland Books, Little, Brown and Company','Qui expedita sit tempore aliquam ut eos. Et quo provident exercitationem praesentium at eveniet rerum. Laborum facere animi soluta voluptas quos. Pariatur ea quibusdam eos sunt. Mollitia aut odit ut in. Consequatur autem velit rerum quos. Ipsa cupiditate consequatur saepe consequatur vitae. Sit et quia ad minima aliquam suscipit molestiae non.','2023-12-13 16:35:33','2023-12-13 16:35:33'),
	 ('LGF','Quaerat possimus voluptates quaerat veniam. Sapiente enim commodi qui ut. Harum et sit voluptatum voluptas. Iure reprehenderit facilis expedita et doloribus quidem voluptas. Ut laborum sint officiis sit ut vel at.','2023-12-13 16:35:33','2023-12-13 16:35:33'),
	 ('Bloomsbury Publishing PLC, UK','Sunt fuga harum est error. Sit alias ducimus pariatur beatae perferendis nihil autem. Sunt magni eaque dolores. Odio doloremque cumque et et accusantium nemo nisi. Quo accusantium commodi consequatur et. In dolores laudantium totam unde dolores.','2023-12-13 16:35:34','2023-12-13 16:35:34'),
	 ('Media Rodzina','Distinctio labore minus quidem perspiciatis in. Sed facilis rerum ut totam architecto dolorum aut accusantium. Eos quo non quis eligendi.','2023-12-13 16:35:34','2023-12-13 16:35:34'),
	 ('Carlsen Verlag Gmbtl','Ratione molestiae consequuntur quas qui tempore. Consequatur aut qui eveniet iure dicta dolore blanditiis. Id aut aut quisquam illum ut nesciunt. In et deserunt quis. Dolores ad veritatis et. Sed ipsam quis qui sed aut non.','2023-12-13 16:35:34','2023-12-13 16:35:34'),
	 ('Salamandra Infantil y Juvenil','Dolores cumque ea nihil expedita assumenda et. Iste tempora repellendus tempora. Ratione ducimus rerum ipsum ratione quae. Officia facilis omnis consequatur quibusdam. Et provident minus saepe incidunt voluptatem dolor ea.','2023-12-13 16:35:34','2023-12-13 16:35:34'),
	 ('Little, Brown Book Group Limited','Voluptas adipisci tempora debitis molestiae deleniti atque est. Ducimus quisquam dolorem in et consequatur perferendis. Omnis ad sed et et numquam non corporis voluptas. Officia sapiente odio dolores fugiat quas dolor molestiae.','2023-12-13 16:35:34','2023-12-13 16:35:34'),
	 ('Editorial Empúries','Qui mollitia nesciunt labore quisquam. Facere quisquam tempore perspiciatis possimus placeat dignissimos. Non at voluptate eos iste quos. Ipsa iure ut consequuntur voluptatem. Quasi neque sed vitae et ipsum repellat. Odit odit et voluptas culpa.','2023-12-13 16:35:34','2023-12-13 16:35:34');
INSERT INTO Authors (Name, Biography, CreatedAt, UpdatedAt) VALUES
	 ('LITTLE BROWN USA.','Quaerat fugit alias repudiandae laboriosam quos omnis nesciunt. Consequatur natus dolor illum consequatur esse doloribus in. Ab sunt quidem nobis atque beatae corrupti commodi. Magni tenetur et doloremque consequatur. Quia assumenda aliquid qui ut quisquam et architecto.','2023-12-13 16:35:34','2023-12-13 16:35:34'),
	 ('Disney Hyperion','Aliquid eveniet sint ab et. Earum quam qui officia ut. Iste voluptatem voluptatibus facere accusantium voluptatem magni fugit. Modi enim culpa natus veritatis autem eligendi est. Amet ea soluta dolorem porro rerum cupiditate. Sequi et minima illum aperiam optio numquam. Vitae tempore aut sit aperiam quae nostrum. Et sed dolores veritatis harum.','2023-12-13 16:35:34','2023-12-13 16:35:34'),
	 ('ĖKSMO','Optio a unde corrupti sit necessitatibus. Fuga veniam voluptatum libero qui aut ut ut sapiente. Rerum molestias rerum qui vero adipisci architecto fuga. Deleniti eum facilis sed velit eaque.','2023-12-13 16:35:35','2023-12-13 16:35:35'),
	 ('Puffin / Penguin Books','Labore vero illum aut sunt cumque laborum. Commodi in ipsum animi in repudiandae totam sit. Autem dolores ut magnam. Ea quaerat eaque ipsam. Autem voluptates hic et non totam mollitia possimus. Est ipsa doloremque et nisi. Inventore recusandae ratione esse est ut eum porro. Quaerat ut recusandae aliquid repudiandae.','2023-12-13 16:35:35','2023-12-13 16:35:35'),
	 ('Perfection Learning','Deserunt delectus mollitia et esse qui. Quaerat maxime unde ducimus laudantium sint aut. Aut minima ut aliquid autem doloribus amet laboriosam. Esse ex dolores temporibus. Nesciunt quo quae quo est numquam earum natus. Est rerum amet aut nihil quod quasi. Repellendus delectus nihil amet ab dignissimos.','2023-12-13 16:35:35','2023-12-13 16:35:35'),
	 ('Hyperion Paperbacks for Children','Vel ratione nostrum quo et sint et dolores ab. Id voluptatem et eligendi et. Fuga est aut totam esse magni. Occaecati ut quidem autem. Velit sed culpa earum libero quasi. Voluptatum incidunt dolorum fuga saepe velit. Nisi facilis cupiditate omnis eligendi repellat. Corrupti corporis voluptas esse porro accusantium.','2023-12-13 16:35:36','2023-12-13 16:35:36'),
	 ('Galaxy','Inventore cum cum iste consequatur sint vel. Est ea maiores corrupti qui nostrum. Blanditiis quo aut molestiae. Explicabo sit laudantium sit. Et omnis incidunt illum amet. Consequatur quod qui vitae provident dolores veniam sint facere. Quo quibusdam qui dolorem eius animi sit at.','2023-12-13 16:35:36','2023-12-13 16:35:36'),
	 ('Disney-Hyperion Books','Labore qui nisi qui et. Rerum fuga accusamus voluptatibus quibusdam eum. Ea exercitationem consequatur ut aut laudantium porro. Sunt tempore impedit tempore minima dolor nulla labore. Deleniti neque quia non. Et quibusdam quis aut ipsam consectetur. Blanditiis doloribus qui qui sapiente assumenda. Sed dolor et dolorem dolorum ea eos cupiditate.','2023-12-13 16:35:36','2023-12-13 16:35:36'),
	 ('','Odio molestiae officia inventore ducimus ut et assumenda et. Et ea ea eaque possimus excepturi. Quas qui dignissimos et culpa aut rerum. Assumenda adipisci temporibus dolores quasi dicta repellat quis eos. Dolores vel quia nam voluptatum eveniet doloremque. Illo iste est dolorem ratione saepe incidunt. Qui qui voluptatem pariatur numquam quia qui.','2023-12-13 16:35:37','2023-12-13 16:35:37'),
	 ('Puffin Books','Veniam ut ea enim id quia voluptatem. Quisquam aperiam iure asperiores aspernatur corrupti hic distinctio. Veniam quas amet et perferendis aspernatur.','2023-12-13 16:35:37','2023-12-13 16:35:37');
INSERT INTO Authors (Name, Biography, CreatedAt, UpdatedAt) VALUES
	 ('Yuan Liu/Tsai Fong Books','Id impedit dolorem id nemo aperiam perferendis et. Sed consequatur explicabo nostrum deleniti odio. Dolorum ipsa autem delectus consequatur maiores nemo occaecati. Aut et et fugiat qui. Quae quos ut dolores doloribus. Autem vero ipsam aperiam itaque ad aut nostrum eos. Magnam natus earum aut ea.','2023-12-13 16:35:38','2023-12-13 16:35:38'),
	 ('Disney-Hyperion','Atque aut deserunt molestiae possimus rerum dicta a. Nisi quia doloremque laborum ut voluptate incidunt rem. Laudantium commodi dolorem cupiditate occaecati alias magnam sed quos. Facilis accusantium assumenda numquam eaque quisquam similique sint. Velit consectetur provident non deserunt.','2023-12-13 16:35:38','2023-12-13 16:35:38'),
	 ('Thorndike Press','Magni possimus odit magni et veritatis et esse. Ut quo quaerat eius est dolores delectus sit. Corrupti quaerat doloribus animi vitae impedit quis libero. Expedita labore et eos aliquid magni. Et excepturi quidem ipsa dolor voluptate eaque nostrum in. Vel dolor delectus explicabo odio quibusdam.','2023-12-13 16:35:38','2023-12-13 16:35:38'),
	 ('Hyperion Books for Children','Recusandae rem est voluptatem eaque nobis et impedit. Tenetur nesciunt cupiditate facilis odit deleniti saepe ut maxime. Sit voluptatem beatae distinctio consequatur. Consectetur eaque blanditiis placeat recusandae. Voluptates velit laboriosam accusamus. Perspiciatis aut pariatur ea dicta repellendus.','2023-12-13 16:35:39','2023-12-13 16:35:39'),
	 ('Disney - Hyperion','Nostrum quo qui qui fuga. Ratione ab unde nemo enim nam. Vel unde id recusandae laudantium. Voluptas voluptatem quia illo est eligendi ducimus et. Rerum unde placeat non est omnis voluptas. Ipsam nihil similique quasi officiis ut. Ullam deserunt voluptas esse consequatur voluptatem non. Delectus nam ut voluptates voluptas doloribus fugiat aliquid.','2023-12-13 16:35:39','2023-12-13 16:35:39'),
	 ('Recorded Books, Inc. and Blackstone Publishing','Omnis aut ut quisquam cum in qui. Voluptas a tenetur vel enim et ab. Aut sunt tempora id consequatur et. Nulla iusto voluptatum sed doloremque magnam totam. Culpa omnis iure ipsum illo reprehenderit. Qui aut architecto et autem. Accusantium ut et non optio dicta minus quia. Nam nobis enim eaque expedita reprehenderit.','2023-12-13 16:35:39','2023-12-13 16:35:39'),
	 ('Scholastic Inc.','Ullam tempore deleniti quo qui ipsa. Officiis repellendus recusandae eos ipsum. Eligendi delectus eius rerum odio et. Quia quia deleniti sed quo. Odio quam impedit tempore eum voluptate. Cumque quo eveniet vitae. Quidem recusandae accusantium aut est ipsa. Dolore sint totam molestias facere.','2023-12-13 16:35:39','2023-12-13 16:35:39'),
	 ('Random House Publishing Group','Maxime sit facilis aperiam rerum occaecati. Molestiae sint omnis est et. Non nulla et accusantium qui est illo nam. In dolores et voluptatem similique. Sunt nulla suscipit et. Blanditiis cum corporis accusantium voluptatem dolor ipsa dolores.','2023-12-13 16:35:40','2023-12-13 16:35:40'),
	 ('Bantam Books','Harum aut deserunt vitae enim velit optio. Atque deserunt provident reprehenderit. Sit quod quis culpa exercitationem pariatur reprehenderit vel. Sed similique beatae harum maiores consequatur ea nam.','2023-12-13 16:35:40','2023-12-13 16:35:40'),
	 ('Albin Michel','Fuga voluptas eum voluptas eligendi. Aut quasi natus autem cumque ut est sed quia. Eius dolorem rerum et in ducimus. Et corporis soluta animi aspernatur quibusdam deserunt.','2023-12-13 16:35:40','2023-12-13 16:35:40');
INSERT INTO Authors (Name, Biography, CreatedAt, UpdatedAt) VALUES
	 ('Unknown Publisher','Ipsa possimus sunt voluptatibus doloremque officia atque. Dignissimos veniam odio iusto quia. Ea dolorum impedit omnis quo optio recusandae.','2023-12-13 16:35:40','2023-12-13 16:35:40'),
	 ('Marco Book Company','Quo nulla in eaque laborum dolores deleniti vel. Nisi laborum nihil distinctio expedita corporis nesciunt. Sunt ratione sed ab dolorem est sapiente et. Dolores et possimus non in. Consectetur at est architecto autem. Exercitationem dolor rem asperiores quia. Voluptatem distinctio dolorem et culpa saepe.','2023-12-13 16:35:40','2023-12-13 16:35:40'),
	 ('Berkley','Magnam mollitia saepe in est praesentium omnis minima. Tempora doloremque dolor et est ipsum dolorem sapiente. Ullam ut natus qui. Modi praesentium atque aspernatur dicta rem. Autem dolores qui maxime exercitationem est qui eum. Voluptas maxime deserunt quam ipsum praesentium ea nihil. A maxime culpa temporibus amet.','2023-12-13 16:35:41','2023-12-13 16:35:41'),
	 ('ROLYET','Itaque est nam debitis porro neque quis. Velit ea cupiditate non ullam occaecati voluptatibus rerum. Et tempora vel quod voluptatibus possimus maxime velit qui. Labore reiciendis animi nulla voluptatem nemo ipsum.','2023-12-13 16:35:41','2023-12-13 16:35:41'),
	 ('France Loisirs','Neque mollitia quo nisi doloribus culpa placeat. Officiis repellendus quia laudantium temporibus ducimus. Qui rem laboriosam rerum non id architecto. Praesentium magni qui nobis qui quis. Ut dolores aut sunt repellat ullam. Itaque soluta reiciendis tempora ullam magnam vel officia.','2023-12-13 16:35:41','2023-12-13 16:35:41'),
	 ('Heyne','Incidunt sunt dolor non eaque adipisci magnam eligendi. Soluta incidunt fugiat cum rerum non eum aliquam. Architecto optio ipsa est nihil.','2023-12-13 16:35:42','2023-12-13 16:35:42'),
	 ('ACT','Molestiae labore recusandae voluptas est tenetur et. Et eius sequi consequuntur temporibus quae ut sit. Sit necessitatibus deleniti aut ut est a. Provident in quia enim id voluptas. Atque ut aut odit aut. Dolores magni sunt tempore. Voluptatem nam enim quis sit cumque in voluptas. Eius quae ea autem assumenda ea.','2023-12-13 16:35:42','2023-12-13 16:35:42'),
	 ('Sine nomine','Molestiae velit fugiat et nemo repudiandae. Omnis autem sint ipsum cumque non commodi. Officia voluptatem quae vero et ipsam laborum autem. Minus earum ut facilis aut ea id amet. Aut quae ut in expedita est ipsum hic. Itaque maxime non odit in perspiciatis quisquam veniam.','2023-12-13 16:35:43','2023-12-13 16:35:43'),
	 ('Sperling paperback','Aut quisquam sequi earum et sunt. A suscipit totam et laudantium. Sequi perferendis sit mollitia. Commodi autem qui est odio. Quas quaerat occaecati odit officia suscipit. Dolorum quaerat beatae expedita. Non eius aut nam nostrum id rerum. Temporibus sequi esse itaque provident aut expedita quia.','2023-12-13 16:35:43','2023-12-13 16:35:43'),
	 ('Penguin USA, Inc.','A fugiat dolore beatae quia earum repellat quod. Reiciendis qui quaerat voluptatum saepe. Sit magnam id sequi adipisci. Pariatur est officiis soluta consequuntur explicabo voluptas. Repellendus voluptates sed laudantium dolor ut et sed. Aut ad fugit aut omnis sed labore. Dolorem fugiat voluptas omnis beatae.','2023-12-13 16:35:44','2023-12-13 16:35:44');
INSERT INTO Authors (Name, Biography, CreatedAt, UpdatedAt) VALUES
	 ('DEBOLSILLO','Officia autem autem consequatur accusantium ipsam ipsam. Non aut ut et ex vero. Ut repudiandae sit omnis. Similique reiciendis veritatis mollitia voluptatum occaecati amet corporis perspiciatis. Expedita architecto quia neque accusamus. Ut rerum sunt magnam aspernatur.','2023-12-13 16:35:44','2023-12-13 16:35:44'),
	 ('Ullstein','Molestias eaque ut eos eius. Quo voluptates veritatis eaque vel hic eveniet. Eius laboriosam et aliquid suscipit asperiores. Dolore voluptatibus impedit dolor ullam et. Cupiditate magni delectus sit rerum. Facilis asperiores voluptate aut quasi.','2023-12-13 16:35:45','2023-12-13 16:35:45'),
	 ('PLAZA Y JANES','Et qui tenetur non iusto. Consequatur eum aut voluptatem. Facere eligendi at incidunt debitis. Autem placeat ea labore sed eum cupiditate. Similique id tempora et molestiae iusto cumque. Voluptatem ut est eum fugit sapiente aut excepturi. Quia animi nesciunt asperiores aut autem dicta. Placeat soluta et excepturi perspiciatis saepe illo.','2023-12-13 16:35:46','2023-12-13 16:35:46'),
	 ('Doubleday','Ut qui eius qui ab ea sapiente ex. Vel facilis officia est eius. Placeat asperiores molestiae fugiat quas. Architecto fugiat sed ipsum impedit omnis quam. Non tempore numquam ut reprehenderit vero.','2023-12-13 16:35:46','2023-12-13 16:35:46'),
	 ('Signet','Est est tempore doloremque assumenda ut animi. Nihil illum est harum iure quo eos eveniet enim. Et sit magni fuga nulla dolorem. Voluptas aliquid voluptate voluptas. Velit est voluptas nam. Et ea placeat eos omnis quasi sed. Omnis ad aut et ab reiciendis voluptatum.','2023-12-13 16:35:47','2023-12-13 16:35:47'),
	 ('Heyne Verlag','Provident porro consequatur explicabo sequi optio non dolor. Earum qui dolores dicta sapiente. Assumenda est et labore odit eum doloremque laborum vitae. Qui placeat nesciunt possimus. Omnis libero qui eveniet tempora rerum fuga velit non. Ad inventore repellendus vitae. Et nam fugiat nihil autem. Enim doloribus deleniti architecto qui illum iure.','2023-12-13 16:35:48','2023-12-13 16:35:48');

